print("Введите вид питомца:")
pet = input()
print("Введите возраст питомца:")
age = input()
print("Введите имя питомца:")
name = input()
print("Это " + pet + " по кличке " + name + ".Возраст: " + age + " лет.")