print("Введите поочередно стороны прямоугольника:")
side1 = float(input())
side2 = float(input())
print("Площадь прямоугольника: ", side1 * side2)
print("Периметр прямоугольника: ", 2 * (side1 + side2))